- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.bashrc.d:
      path: bashrc.d/*
      exclude: [bashrc.d/*.noauto.sh]
      glob: true
      create: true
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.emacs.d: emacs.d/
    ~/.gitconfig: gitconfig
    ~/.hgrc: hgrc
    ~/.profile: profile
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc

- defaults:
    link:
      if: '[[ "$(uname)" == "Darwin" ]]'

- link:
    ~/.bashrc.d/macos-bash-completion.sh: bashrc.d/macos-bash-completion.noauto.sh

- shell:
  - [git submodule update --init --recursive, Installing submodules]

- shell:
  - mkdir -p ~/.local/bin
  - ["curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ./.local/bin/z", Installing z]
  - ["curl -Ls https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-unknown-linux-musl.tar.gz | tar xz -C ~/.local/bin --strip-components=1 ripgrep-12.1.1-x86_64-unknown-linux-musl/rg", Installing ripgrep]
  - ["curl -Ls https://github.com/junegunn/fzf/releases/download/0.27.1/fzf-0.27.1-linux_amd64.tar.gz | tar xz -C ~/.local/bin", Installing fzf]
  - chmod -R 0755 ~/.local/bin
