- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.ackrc: ackrc
    ~/.bash_aliases: bash_aliases
    ~/.bash_exports: bash_exports
    ~/.bash_functions: bash_functions
    ~/.bash_profile: bash_profile
    ~/.bash_prompt: bash_prompt
    ~/.bashrc: bashrc
    ~/.emacs.d: emacs.d/
    ~/.gitconfig: gitconfig
    ~/.hgrc: hgrc
    ~/.profile: profile
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]

- shell:
  - ["git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell", Installing base16-shell]

- shell:
  - mkdir -p ~/.local/bin
  - ["curl https://beyondgrep.com/ack-2.14-single-file -o ~/.local/bin/ack", Installing ack]
  - ["curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z", Installing z]
  - chmod -R 0755 ~/.local/bin
