- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.ackrc: ackrc
    ~/.bash_aliases: bash_aliases
    ~/.bash_exports: bash_exports
    ~/.bash_functions: bash_functions
    ~/.bash_profile: bash_profile
    ~/.bash_prompt: bash_prompt
    ~/.bashrc: bashrc
    ~/.boot_jvm_options: boot_jvm_options
    ~/.emacs.d: emacs.d/
    ~/.gitconfig: gitconfig
    ~/.hgrc: hgrc
    ~/.profile: profile
    ~/.profile.boot: profile.boot
    ~/.screenrc: screenrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
