- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.bashrc.d:
      path: bashrc.d/*
      exclude: [bashrc.d/*.noauto.sh]
      glob: true
      create: true
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.emacs.d: emacs.d/
    ~/.gitconfig: gitconfig
    ~/.profile: profile
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc

- defaults:
    link:
      if: '[[ "$(uname)" == "Darwin" ]]'

- link:
    ~/.bashrc.d/macos-bash-completion.sh: bashrc.d/macos-bash-completion.noauto.sh

- shell:
  - [git submodule update --init --recursive, Installing submodules]

- shell:
  - mkdir -p ~/.local/bin
  - ["curl https://raw.githubusercontent.com/rupa/z/master/z.sh -o ~/.local/bin/z", Installing z]
  - chmod -R 0755 ~/.local/bin
